# Generated by Django 4.2.1 on 2023-06-08 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Assignment', '0003_userpostmodel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofilemodel',
            name='bio',
            field=models.TextField(blank=True, null=True),
        ),
    ]
