# Generated by Django 4.2.1 on 2023-06-08 06:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Assignment', '0004_alter_userprofilemodel_bio'),
    ]

    operations = [
        migrations.AddField(
            model_name='userpostmodel',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_post_followers', to='User_Assignment.usermodel'),
        ),
        migrations.AddField(
            model_name='userpostmodel',
            name='likes',
            field=models.ManyToManyField(blank=True, related_name='user_post_likes', to='User_Assignment.usermodel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='gender',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
