# Generated by Django 4.2.1 on 2023-06-08 08:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('User_Assignment', '0005_userpostmodel_follows_userpostmodel_likes_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userpostmodel',
            name='follows',
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='followers',
            field=models.ManyToManyField(to='User_Assignment.usermodel'),
        ),
        migrations.AddField(
            model_name='userprofilemodel',
            name='follows',
            field=models.ManyToManyField(blank=True, related_name='user_post_followers', to='User_Assignment.usermodel'),
        ),
    ]
